[arch]
install_command = "sudo pacman -S --asdeps kicad-library kicad-library-3d --noconfirm"

[debian]
install_command = "exit 1"

[ubuntu]
install_command = "exit 1"

[fedora]
install_command = "exit 1"
