[ubuntu]
install_system = "freecad"
snap = "classic"

[debian]
install_system = "freecad"

[arch]
install_system = "org.freecad.FreeCAD"
flatpak = true

[fedora]
install_system = "org.freecad.FreeCAD"
flatpak = true



