[ubuntu]
dependencies = ["apt-steam"]
install_system = "steam"

[debian]
dependencies = ["apt-steam"]
install_system = "steam"

[arch]
dependencies = ["arch-multilib"]
install_system = "steam"

[fedora]
dependencies = ["rpmfusion"]
install_system = "steam"
